import { Inter, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "300", "400", "500", "700", "900"]});

export const metadata = {
  title: "Compra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <div className="">
        {children}
        </div>
      </body>
    </html>
  );
}
