import {Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { ProductsProvider } from "@/context/ProductsContext";

const poppins = Lato({ subsets: ["latin"], weight: ["100", "300", "400", "700", "900"] });

export const metadata = {
  title: "Compra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ProductsProvider>
        <body className={poppins.className}>
          <Navbar />
          <div className="">
            {children}
          </div>
          <Footer />
        </body>
      </ProductsProvider>
    </html>
  );
}
